preload = /home/nmgui/.config/hypr/wallpapers/lofi_wallpaper.png

wallpaper = HDMI-A-1,/home/nmgui/.config/hypr/wallpapers/lofi_wallpaper.png
wallpaper = DP-3,/home/nmgui/.config/hypr/wallpapers/lofi_wallpaper.png
