$mainMod = SUPER
$scriptsFile = $HOME/.config/hypr/configs/scripts.sh


# Apps
bind = $mainMod, Return, exec, $scriptsFile --terminal
bind = $mainMod, Space, exec, $scriptsFile --app_launcher

# Debug
bind = $mainMod, R, exec, $scriptsFile --refresh

# Scripts
bind = $mainMod, Q, exec, $scriptsFile --kill_active_process
bind = $mainMod, F9, exec, $scriptsFile --dec_volume
bind = $mainMod, F10, exec, $scriptsFile --inc_volume
bind = $mainMod Shift, S, exec, $scriptsFile --screenshot

# Focus
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
